<?php
/**
 * @var \Avalon\Dskapipayment\Block\CartButtons $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->getDskapiStatus() == "1" && $block->getStatus()) { ?>
    <div id="dskapi-cart-button-container" style="margin-top: <?= $escaper->escapeHtmlAttr((string) $block->getDskapiGap()) ?>px;">
        <?php if ($block->getParamsDskapi()->dsk_zaglavie != '') { ?>
            <div class="dskapi_button_div_txt">
                <?= $escaper->escapeHtml($block->getParamsDskapi()->dsk_zaglavie) ?>
            </div>
        <?php } ?>
        <?php if ($escaper->escapeHtml($block->getParamsDskapi()->dsk_custom_button_status == 1)) { ?>
            <img
                id="btn_dskapi_cart"
                class="dskapi_btn_click dskapi_logo"
                src="<?= $escaper->escapeHtml($block->getDskapiButtonNormalCustom()) ?>"
                alt="Кредитен калкулатор DSK Credit"
                onmouseover="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonHoverCustom()) ?>'"
                onmouseout="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonNormalCustom()) ?>'" />
        <?php } else { ?>
            <?php if ($escaper->escapeHtml($block->getParamsDskapi()->dsk_isvnoska == 1)) { ?>
                <table class="dskapi_table_img">
                    <tr>
                        <td class="dskapi_button_table">
                            <img
                                id="btn_dskapi_cart"
                                class="dskapi_btn_click dskapi_logo"
                                src="<?= $escaper->escapeHtml($block->getDskapiButtonNormal()) ?>"
                                alt="Кредитен калкулатор DSK Credit"
                                onmouseover="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonHover()) ?>'"
                                onmouseout="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonNormal()) ?>'" />
                        </td>
                    </tr>
                    <tr>
                        <td class="dskapi_button_table">
                            <p><span id="dskapi_vnoski_txt"><?= $escaper->escapeHtml($block->getParamsDskapi()->dsk_vnoski_default) ?></span> x <span id="dskapi_vnoska_txt"><?= $escaper->escapeHtml(number_format($block->getParamsDskapi()->dsk_vnoska, 2, '.', '')) ?></span> <?= $escaper->escapeHtml($block->getDskapiSign()) ?></p>
                        </td>
                    </tr>
                </table>
            <?php } else { ?>
                <img
                    id="btn_dskapi_cart"
                    class="dskapi_btn_click dskapi_logo"
                    src="<?= $escaper->escapeHtml($block->getDskapiButtonNormal()) ?>"
                    alt="Кредитен калкулатор DSK Credit"
                    onmouseover="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonHover()) ?>'"
                    onmouseout="this.src='<?= $escaper->escapeHtml($block->getDskapiButtonNormal()) ?>'" />
            <?php } ?>
        <?php } ?>
    </div>
    <input
        type="hidden"
        id="dskapi_price"
        value="<?= $escaper->escapeHtml($block->getPrice()) ?>" />
    <input
        type="hidden"
        id="dskapi_cid"
        value="<?= $escaper->escapeHtml($block->getDskapiCid()) ?>" />
    <input
        type="hidden"
        id="dskapi_product_id"
        value="<?= $escaper->escapeHtml($block->getCartProductId()) ?>" />
    <input
        type="hidden"
        id="DSKAPI_LIVEURL"
        value="<?= $escaper->escapeHtml($block->getDskapiLiveUrl()) ?>" />
    <input
        type="hidden"
        id="dskapi_getproductcustom_url"
        value="<?= $escaper->escapeUrl($block->getGetProductCustomUrl()) ?>" />
    <input
        type="hidden"
        id="dskapi_button_status"
        value="<?= $escaper->escapeHtml($block->getParamsDskapi()->dsk_button_status) ?>" />
    <input
        type="hidden"
        id="dskapi_maxstojnost"
        value="<?= $escaper->escapeHtml($block->getParamsDskapi()->dsk_maxstojnost) ?>" />
    <input
        type="hidden"
        id="dskapi_eur"
        value="<?= $escaper->escapeHtml($block->getEur()) ?>" />
    <input
        type="hidden"
        id="dskapi_currency_code"
        value="<?= $escaper->escapeHtml($block->getCurrencyCode()) ?>" />
    <div
        id="dskapi-product-popup-container"
        class="modalpayment_dskapi">
        <div class="modalpayment-content_dskapi">
            <div id="dskapi_body">
                <div class="dskapi_PopUp_Detailed_v1">
                    <div class="dskapi_Mask">
                        <img class="dskapi_header dskapi_header--desktop" src="<?= $escaper->escapeUrl($block->getDskapiPopupImageDesktopUrl()) ?>" alt="" />
                        <img class="dskapi_header dskapi_header--mobile" src="<?= $escaper->escapeUrl($block->getDskapiPopupImageMobileUrl()) ?>" alt="" />
                        <p class="dskapi_product_name">Купи на
                            изплащане със стоков кредит от Банка ДСК</p>
                        <div class="dskapi_body_panel_txt3">
                            <div class="dskapi_body_panel_txt3_left">
                                <p>
                                    • Улеснена процедура за електронно подписване<br />
                                    • Атрактивни условия по кредита<br />
                                    • Параметри изцяло по Ваш избор<br />
                                    • Одобрение до няколко минути изцяло онлайн
                                </p>
                            </div>
                            <div class="dskapi_body_panel_txt3_right">
                                <select
                                    id="dskapi_pogasitelni_vnoski_input"
                                    class="dskapi_txt_right"
                                    onchange="dskapi_pogasitelni_vnoski_input_change();"
                                    onfocus="dskapi_pogasitelni_vnoski_input_focus(this.value);">
                                    <?php for ($i = 3; $i <= 48; $i++) { ?>
                                        <?php if ($block->getVnoskiVisibleArr()[$i]) { ?>
                                            <option
                                                value="<?= $escaper->escapeHtml($i) ?>"
                                                <?php if ($block->getParamsDskapi()->dsk_vnoski_default == $i) {
                                                    echo "selected";
                                                }
                                                ?>><?= $escaper->escapeHtml($i) ?> месеца</option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                                <div class="dskapi_sumi_panel">
                                    <div class="dskapi_kredit_panel">
                                        <div class="dskapi_sumi_txt">Размер на кредита /<?= $escaper->escapeHtml($block->getDskapiSign()) ?>/</div>
                                        <div>
                                            <input
                                                class="dskapi_mesecna_price"
                                                type="text"
                                                id="dskapi_price_txt"
                                                readonly="readonly"
                                                value="<?= $escaper->escapeHtml(number_format($block->getPrice(), 2, ".", "")) ?>" />
                                        </div>
                                    </div>
                                    <div class="dskapi_kredit_panel">
                                        <div class="dskapi_sumi_txt">Месечна вноска /<?= $escaper->escapeHtml($block->getDskapiSign()) ?>/</div>
                                        <div>
                                            <input
                                                class="dskapi_mesecna_price"
                                                type="text"
                                                id="dskapi_vnoska"
                                                readonly="readonly"
                                                value="<?= $escaper->escapeHtml(number_format($block->getParamsDskapi()->dsk_vnoska, 2, ".", "")) ?>" />
                                        </div>
                                    </div>
                                </div>
                                <div class="dskapi_sumi_panel">
                                    <div class="dskapi_kredit_panel">
                                        <div class="dskapi_sumi_txt">Обща дължима сума /<?= $escaper->escapeHtml($block->getDskapiSign()) ?>/</div>
                                        <div>
                                            <input
                                                class="dskapi_mesecna_price"
                                                type="text"
                                                id="dskapi_obshtozaplashtane"
                                                readonly="readonly"
                                                value="<?= $escaper->escapeHtml(number_format($block->getParamsDskapi()->dsk_vnoska * $block->getParamsDskapi()->dsk_vnoski_default, 2, ".", "")); ?>" />
                                        </div>
                                    </div>
                                    <div class="dskapi_kredit_panel">
                                        <div class="dskapi_sumi_txt">ГПР /%/</div>
                                        <div>
                                            <input
                                                class="dskapi_mesecna_price"
                                                type="text"
                                                id="dskapi_gpr"
                                                readonly="readonly"
                                                value="<?= $escaper->escapeHtml(number_format($block->getParamsDskapi()->dsk_gpr, 2, ".", "")) ?>" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="dskapi_body_panel_txt4">
                            Изчисленията са направени при допускането за първа падежна дата след 30 дни и са с насочваща
                            цел. Избери най-подходящата месечна вноска.
                        </div>
                        <div class="dskapi_body_panel_footer">
                            <div
                                class="dskapi_btn"
                                id="dskapi_buy_credit">Купи на изплащане</div>
                            <div
                                class="dskapi_btn_cancel"
                                id="dskapi_back_credit">Откажи</div>
                            <div class="dskapi_body_panel_left">
                                <div class="dskapi_txt_footer">Ver. <?= $escaper->escapeHtml($block->getModuleVersion()) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php
}
?>